import './global.css'
import i18n from '../i18n'
export const metadata = {
  title: "Tourism",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
